spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root

logging:
  level:
    root: warn
    com.holic: info
  file:
    name: D:/log/springboot/pro.log
    max-history: 30
    max-size: 30MB
    total-size-cap: 500MB

server:
  port: 8081
