spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    data-username: root
    password: root

logging:
  level:
    root: warn
    com.holic: info
  file:
    path: E:/log
    name: log-pro

server:
  port: 8081
